/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const RECEIPT_DISCRIMINATOR = new Uint8Array([
  39, 154, 73, 106, 80, 102, 145, 153,
]);

export function getReceiptDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(RECEIPT_DISCRIMINATOR);
}

export type Receipt = { discriminator: ReadonlyUint8Array; bump: number };

export type ReceiptArgs = { bump: number };

export function getReceiptEncoder(): FixedSizeEncoder<ReceiptArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['bump', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: RECEIPT_DISCRIMINATOR })
  );
}

export function getReceiptDecoder(): FixedSizeDecoder<Receipt> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['bump', getU8Decoder()],
  ]);
}

export function getReceiptCodec(): FixedSizeCodec<ReceiptArgs, Receipt> {
  return combineCodec(getReceiptEncoder(), getReceiptDecoder());
}

export function decodeReceipt<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Receipt, TAddress>;
export function decodeReceipt<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Receipt, TAddress>;
export function decodeReceipt<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Receipt, TAddress> | MaybeAccount<Receipt, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getReceiptDecoder()
  );
}

export async function fetchReceipt<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Receipt, TAddress>> {
  const maybeAccount = await fetchMaybeReceipt(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeReceipt<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Receipt, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeReceipt(maybeAccount);
}

export async function fetchAllReceipt(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Receipt>[]> {
  const maybeAccounts = await fetchAllMaybeReceipt(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeReceipt(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Receipt>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeReceipt(maybeAccount));
}

export function getReceiptSize(): number {
  return 9;
}
