[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
descipline = "5how19SLnecRwk7hQBrEKU3bF8KwH3Z6vXUDiwGssFFc"

[programs.localnet]
descipline = "5how19SLnecRwk7hQBrEKU3bF8KwH3Z6vXUDiwGssFFc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/fc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
