[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
descipline = "2s3weLk9GXoqkbw377YbiQpfQX1eQ6DxUsfHi82WRZLF"

[programs.localnet]
descipline = "2s3weLk9GXoqkbw377YbiQpfQX1eQ6DxUsfHi82WRZLF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "data/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
