[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
descipline = "HHviGr7n1GBLvSf51pjrPpXtxzkJCNghioR5cCMELskS"

[programs.devnet]
descipline = "HHviGr7n1GBLvSf51pjrPpXtxzkJCNghioR5cCMELskS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/fc/.config/solana/id_1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
