/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum TokenAllowed {
  WSOL,
  USDC,
}

export type TokenAllowedArgs = TokenAllowed;

export function getTokenAllowedEncoder(): FixedSizeEncoder<TokenAllowedArgs> {
  return getEnumEncoder(TokenAllowed);
}

export function getTokenAllowedDecoder(): FixedSizeDecoder<TokenAllowed> {
  return getEnumDecoder(TokenAllowed);
}

export function getTokenAllowedCodec(): FixedSizeCodec<
  TokenAllowedArgs,
  TokenAllowed
> {
  return combineCodec(getTokenAllowedEncoder(), getTokenAllowedDecoder());
}
